### ISSUE TITLE
Problem installing scfind

### ISSUE THREAD

**Issue by MarkusBoesch93** [hemberg-lab/scfind#63]
Hello,
I get an error message when trying to install scfind and I need help to figure it out, how to fix it.

 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)

devtools::install_github(repo="hemberg-lab/scfind", ref="master")
Downloading GitHub repo hemberg-lab/scfind@master
√  checking for file 'C:\Users\u0125188\AppData\Local\Temp\RtmpG2SLlH\remotes1fcc44932a93\hemberg-lab-scfind-388c394/DESCRIPTION' ...
-  preparing 'scfind':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'scfind_3.5.0.tar.gz'
   
Installing package into ‘C:/Users/u0125188/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'scfind' ...
** using staged installation
** libs

*** arch - i386
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c eliasFano.cpp -o eliasFano.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c fp_growth.cpp -o fp_growth.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c functions.cpp -o functions.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c serialization.cpp -o serialization.o
C:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o scfind.dll tmp.def RcppExports.o eliasFano.o fp_growth.o functions.o serialization.o -LC:/Users/u0125188/DOCUME~1/R/R-3.6.1/bin/i386 -lR
installing to C:/Users/u0125188/Documents/R/win-library/3.6/00LOCK-scfind/00new/scfind/libs/i386

*** arch - x64
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c eliasFano.cpp -o eliasFano.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c fp_growth.cpp -o fp_growth.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c functions.cpp -o functions.o
C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/Users/u0125188/DOCUME~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Users/u0125188/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/u0125188/Documents/R/win-library/3.6/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c serialization.cpp -o serialization.o
C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o scfind.dll tmp.def RcppExports.o eliasFano.o fp_growth.o functions.o serialization.o -LC:/Users/u0125188/DOCUME~1/R/R-3.6.1/bin/x64 -lR
installing to C:/Users/u0125188/Documents/R/win-library/3.6/00LOCK-scfind/00new/scfind/libs/x64
** R
Error : (converted from warning) unable to re-encode 'CoreMethods.R' lines 421, 422, 423, 424, 449, 461, 466, 481, 494, 503
ERROR: unable to collate and parse R files for package 'scfind'
* removing 'C:/Users/u0125188/Documents/R/win-library/3.6/scfind'
Error: Failed to install 'scfind' from GitHub:
  (converted from warning) installation of package ‘C:/Users/u0125188/AppData/Local/Temp/RtmpG2SLlH/file1fcc37eb970/scfind_3.5.0.tar.gz’ had non-zero exit status

**Comment by pati-ni** [comment]
Hi @hjg1008,

it has to do with some  special characters included in the file. Will provide a fix soon.

Thanks for reporting that.

**Comment by pati-ni** [comment]
@hjg1008 I believe the message should go away now
